# -*- coding: utf-8 -*-
"""daterange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMx5e2imCIbBFzd_SMI0n7b_mxP__JuH
"""

# importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ds = pd.read_csv("aapl_no_dates.csv")
ds.shape

# creating a date range
rng = pd.date_range(start = "6-1-2020", end = "6-30-2020", freq = "B") # B for Business days
rng

ds.set_index(rng, inplace = True)

# Now to add missing days(eg working days)
ds.asfreq("D", method="pad") # pad will just copy the the value of upper column

# ploting the graph
ds.Close.plot()

# to find the average of stock prices
ds.Close.mean()

# to find the average stock price ( 1st WEEK ONLY!)
ds["6-1-2020":"6-7-2020"].Close.mean()

# To get the hourly data
ds.asfreq("H", method = "pad")



# when we know the start date but does not know the end date
rng1 = pd.date_range(start = "6-1-2020", periods= 72, freq = "B") # returns next 72 business days
rng1

# Now making a dummy dataset for produced days 
ds1 = pd.DataFrame()
s = pd.Series(np.random.randint(1,10, len(rng1)), index = rng1)
ds1["col"] = s
ds1.head()