# -*- coding: utf-8 -*-
"""Resampling_Datetimeindex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GH0HAIoXrqEqzYkubHVzdCjOgSCz7r37
"""

# Time series analysis
import pandas as pd

# importing the dataset
ds = pd.read_csv("AAPL.csv", parse_dates=["Date"], index_col = ["Date"])

# Now benefits of setting index column to be date
# 1. retrive  data according to a month
ds["2019-7"] # july month data

ds["2019-7"].Close.mean() # average stock price in month of july.

ds["2019-7-1":"2019-7-8"] # returns the range of days (1st week)

# Resampling technique
ds.Close.resample("M").mean()  # monthly mean of each month
ds.Close.resample("W").mean()  # weekly mean

# ploting using resampling
ds.Close.resample("M").mean().plot() # plot average stock price according to month

ds.Close.resample("M").mean().plot(kind = "bar")