# -*- coding: utf-8 -*-
"""shifting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LB1oJx2rogZlYRtsheD5er1jP4Mx_a1P
"""

# shifting and lagging
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

ds = pd.read_csv("fb.csv", parse_dates=["Date"], index_col= "Date")
ds

# shifting 1 day
ds1 = ds.shift(1)

# for shifting 3 days
ds1 = ds.shift(3)
ds1

# for reverse shifting the data
ds1.shift(-2)

# now creating comparision of price of one day
ds["one_day"] = ds.shift(1)
ds

# price changes  in one day
ds["changed"] = ds["one_day"]-ds["Price"]
ds

# now calculating the 5 days percentage return
ds["5_day_return"] = (ds["Price"] - ds["Price"].shift(5))*100/ds["Price"].shift(5)*100
ds

# we can also shift the days for that freq = not none
ds.index # now change the frequency to date.

ds.index = pd.date_range(start = "2017-08-15", periods = len(ds), freq  = "B")
ds.index  # now we can change the days!!

ds

# for shifting the days 
ds.tshift(1)   # it add 1 day
ds.tshift(2)    # it add 2 days
ds.tshift(-2)  # it takes us 2 days earlier (13 & 12 is holidays so it gives us 2017-08-11)