# -*- coding: utf-8 -*-
"""Timezone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNN5ecYPGPyLu253retAnJNv2xdvSsIO
"""

# handling time zones of different country
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ds = pd.read_csv("msft.csv", header = 1, index_col=["Date Time"], parse_dates= True)
ds

from pytz import all_timezones
all_timezones

# making it American time zone
ds = ds.tz_localize(tz = "America/Toronto")

ds

# converting this american time to indian timezone
# ds = ds.tz_localize(tz = "Asia/Kolkata") gives error already converted so use tz_convert() both gives the same result
ds = ds.tz_convert(tz="Asia/Kolkata")
ds.index

# now creating a date range
rng = pd.date_range(start = "2016/02/01", periods = 10, tz = "Asia/Kolkata", freq = "H")
m = pd.Series(len(rng), rng)
rng

rng = pd.date_range(start = "2017-08-22 9:00:00", periods = 10, freq = "30min")
s = pd.Series(range(len(rng)), rng)
s

b  = s.tz_localize(tz = "Europe/Berlin")
b

m = s.tz_localize(tz = "Asia/Kolkata")
m

m+b