# -*- coding: utf-8 -*-
"""to_date_time.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JvCtf1m4yEfPbZ0m0VuT1AsDeHXbNJ2L
"""

# Now converting this to datetime
import pandas as pd
# 5 january 2017
dates = ["2017-01-05", "Jan 5, 2017", "01/05/2017", "2017.01.05", "2017/01/05", "20170105"]
dates_with_time = ["2017-01-05 2:30 PM", "Jan 5, 2017 14:30", "01/05/2017"]

pd.to_datetime(dates)

pd.to_datetime(dates_with_time)

# us date format mm/dd/yyyy (Default)
# europe date format dd/mm/yyyy
pd.to_datetime("05/01/2017", dayfirst = True)   # 5 will be considered as day

# universal date conversion format
pd.to_datetime("05$01$$2017",format="%d$%m$$%Y" )  # any character can be replaced in place of $

# to handle errors (not date time values) 
# NaT means Not a Timestamp.
dates = ["2017-01-05", "Jan 5, 2017", "01/05/2017", "2017.01.05", "2017/01/05", "20170105", "abc", "dev"]
dt = pd.to_datetime(dates, errors = "coerce")
dt