# -*- coding: utf-8 -*-
"""1_Resampling_Datetimeindex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2hSmZ0En_kugZaSSdo1IIuv-tG2dhQs
"""

# Time series analysis
import pandas as pd

# importing the dataset
# file name: AAPL.csv, convert Date column in dates and index col.

# Now benefits of setting index column to be date
# 1. retrive  data according to a month
     # july month data

     # average stock price in month of july.

     # returns the range of days (1st week)

# Resampling technique
      # monthly mean of each month
      # weekly mean

# ploting using resampling
     # plot average stock price according to month

# plot bar graph.