# -*- coding: utf-8 -*-
"""5_Periods_PeriodIndex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xxJG5_0FqezO2CAD86lOLSRBrAVAr7R0
"""

# Period and PeriodIndex
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

y = pd.Period("2019")

# Start time

# End time

# we can also create another year by just adding 1.

# we can also change frequency by Months, days ,Hours,
# for months

# start time of month

# it gives end time of month

# it gives the feb month.

# for days

# start time of day

# end time of day

# gives the next day!

# making the period for hour

# start time of the period(hour)

# end time of the period

# gives next hour!

# now Quaters (4 quaters in a year)
     # in freq write when your quater ends

# it gives the start time.

# 31st jan is the ending of the quater

# now period range function

# for epypt period ends in january



# now creating a series
s = pd.Series(np.random.randn(len(pr)), index=pr)
s

# now we can retrive a quater by its year
s["2011"]

# now we can retrive a quater by its yearS
# perform slicing of the years

# converting into the quater into dates

# converting the timestamp into index

# import the dataset for exercise

# performing transposing of the matrix



