# -*- coding: utf-8 -*-
"""6_Timezone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_yR3VPeHFXgD_5yxHjJ5A6QIDPgwOqa
"""

# handling time zones of different country
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# importing the dataset
# file name: msft.csv

# to show the all the possible time zones

# making it American time zone

ds

# converting this american time to indian timezone
# ds = ds.tz_localize(tz = "Asia/Kolkata") gives error already converted so use tz_convert() both gives the same result

# now creating a date range from 2016/02/01 to 10 periods 
# and convert it into series for changing the freq param

# now again creating a date range from 2017-08-22 9:00:00 to 10 periods

# define b
b

# define m
m

# m+b