# -*- coding: utf-8 -*-
"""shifting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19DlQUVkmr354MaK2WHXvF8Z9jKLGl5o2
"""

# shifting and lagging
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# read the data file 
# name: fb.csv & set date to be the index column

# shifting 1 day

# for shifting 3 days

# for reverse shifting the data

# now creating comparision of price of one day

# price changes  in one day

# now calculating the 5 days percentage return

# we can also shift the days for that freq = not none
     # now change the frequency to date.

# now we can change the days!!



# for shifting the days 
       # it add 1 day
        # it add 2 days
      # it takes us 2 days earlier (13 & 12 is holidays so it gives us 2017-08-11)