# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YMpSIP4z6HYxl_tx5tb8tyOXpZTtuN5r
"""

# Crosstab: also known as contengency table, 
# displays the frequency of distribution of varibles

import pandas as pd
ds = pd.read_excel("survey.xls")
ds.head()

# making the contengency table
pd.crosstab(ds.Nationality, ds.Handedness)

# contengency table for sex and handedness
pd.crosstab(ds.Sex, ds.Handedness)

# for multiiple headers
pd.crosstab(ds.Sex, [ds.Handedness, ds.Nationality])

# for chi square format 
pd.crosstab(ds.Sex, ds.Handedness, margins = True)

# now finding the percentage of female who r left handed (16.6%)
# and male who r left handed(41.6%)
pd.crosstab(ds.Sex, ds.Handedness, margins = True, normalize= True)

# now finding the "AVERAGE AGE" of the sexes(males and females)
# and handedness(left or right)
pd.crosstab(ds.Sex, ds.Handedness, values = ds.Age, aggfunc="mean")